# Generated by Django 4.2 on 2023-04-20 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ether_luxe', '0002_collection_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='image_uri',
            field=models.CharField(default='https://ether-luxe.definme.com/images/character1.png', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='token',
            name='level',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='token',
            name='name',
            field=models.CharField(default='Char 1', max_length=255),
            preserve_default=False,
        ),
    ]
