# Generated by Django 4.2 on 2023-04-24 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ether_luxe', '0003_token_image_uri_token_level_token_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='chain',
            name='last_indexed_block_collection',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
