# Generated by Django 4.2 on 2023-04-25 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ether_luxe', '0004_chain_last_indexed_block_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
