# Generated by Django 4.2 on 2023-04-27 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ether_luxe', '0005_token_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_token', to='ether_luxe.collection'),
        ),
        migrations.CreateModel(
            name='SaleToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.DecimalField(decimal_places=0, max_digits=80)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('image_uri', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=256)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_token', to='ether_luxe.collection')),
            ],
        ),
    ]
